name: MasterDeployCI - Theme
on:
  push:
    tags:
      - 'V*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Create Release Folder
      run: | 
        npm i 
        gulp build
    - uses: papeloto/action-zip@v1
      with:
        files: ./WOWFIX
        dest: WOWFIX.zip
    - name: Upload zip folder for release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: WOWFIX.zip
        asset_name: WOWFIX.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Download the WOWFIX.zip file for easy wordpress theme installation"
